name: Flutter_GitHub_Actions Tests
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    # https://stackoverflow.com/a/63122434/436422

    steps:
      # Github repository의 소스를 가져오는 action입니다.
      - name: Checkout source code
        uses: actions/checkout@v1
      # 인스턴스에 Flutter SDK를 설치하는 action 입니다.
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
          # flutter-version: '3.13.6'

      - name: Copy file
        uses: canastro/copy-file-action@master
        with:
          source: ".env.sample"
          target: ".env"

      - name: Test
        run: |
          flutter config --no-analytics
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter test
